create database mira;
use mira; 
show databases; 
show tables;
desc employee;
create table employee(no int, name char(20), salary int, zone char(10),age int, grade char(1), dept int); 
insert into employee values(1,'mukul',30000,'west',28,'A',10);
insert into employee values(2,'kritika',35000,'centre',30,'A',10);
insert into employee values(3,'naveen',32000,'west',40,'NULL',20);
insert into employee values(4,'uday',38000,'north',38,'C',30);
insert into employee values(5,'nupur',32000,'east',26,'NULL',20);
insert into employee values(6,'moksh',37000,'south',28,'B',10);
insert into employee values(7,'shelly',36000,'north',26,'A',30);
select * from employee;
select salary, zone, grade from employee; 
select no, name, salary, zone, age, grade, dept, 12*salary from employee;
select no, name, salary, zone, age, grade, dept, 12*salary 'annual salary' from employee; 
select * from employee where age<30; 
select name from employee where zone='north';
select salary from employee where dept=10; 
select * from employee where grade is NULL; 
select * from employee where grade<> NULL; 
select distinct zone from employee; 
select distinct dept from employee; 
select * from employee where dept=10 and age>30; 
select * from employee where salary>35000 and dept=30; 
select name, salary from employee where zone <> 'west' or zone <> 'centre';
select name from employee where dept in (20,30); 
select * from employee where salary >32000 and salary<38000; 
select * from employee where grade > 'A' and grade <'C'; 
select name from employee where dept in (20,30); 
select name, salary from employee where not(zone)='west' or not(zone)='centre'; 
select * from employee where salary between 32000 and 38000; 
select * from employee where grade between 'A' and 'C'; 
select name, salary, age from employee where name like 'M%';
select name, salary, age from employee where name like '%a';
select name, salary, age from employee where name like '%a%';
select name, salary, age from employee where not(name) like '%a%';
select * from employee where name like '_a%';
select * from employee order by salary;
select * from employee order by name desc;
select * from employee order by grade, salary desc;
select count(*) from employee;
select count(zone) from employee;
select avg(age) from employee where zone='west';
select max(salary) from employee where grade='A';
select sum(salary) from employee where name like 'M%';
select count(*), dept from employee group by dept; 
select max(salary), min(salary), avg(salary), zone group by zone;
select avg(age), dept from employee group by dept having avg(age)>30;
set sql_safe_updates=0;
update employee set Grade='B' where grade is NULL;
update employee set salary=salary+10/100*salary where age>30;
delete from employee where grade='C' and salary<30000;
delete from employee where dept=10 and age>40;
drop table employee;
alter table employee add hiredate date;
alter table employee modify name char(15);
alter table employee change age empage;
create table employee(no int NOT NULL primary key, name char(20), salary int check(salary>20000) , zone char(10),age int, grade char(1), dept int default 10);
create table company(id int NOT NULL primary key, cname char(20), rating int , no int references employee(no));
select employee.name, company.cname from employee, company;
select employee.name, company.cname from employee, company where employee.no=company.no; 
select max(employee.salary), company.city from employee, company where employee.no=com group by city;
create view wemployee as select * from employee where zone='west';
drop view wemployee;
alter table employee add primary key(no); 
alter table employee drop primary key;
