create database Dmart;
use Dmart;
create table Customers(C_id int primary key , C_name char(30) , Age int , Contact int);
create table Products(P_id int primary key , P_name char(30) , Price int);
create table Orders(C_id int ,foreign key(C_id) references Customers(C_id) , P_id int , foreign key(P_id) references Products(P_id) , O_qty int);
desc Customers;
desc Products;
desc Orders;
insert into Customers values(101 , 'Neel' , 23 , 12345 );
insert into Customers values(102 , 'Dev' , 18 , 12345 );
insert into Customers values(103 , 'Anish' , 18 , 12345 );
insert into Customers values(104 , 'Krish' , 20 , 12345 );
insert into Customers values(105 , 'Viraj' , 21 , 12345 );
select * from Customers;
insert into Products values(051 , 'Burger' , 55);
insert into Products values(052 , 'Pizza' , 69);
insert into Products values(053 , 'Ice Cream' , 40);
insert into Products values(054 , 'Cold Drink' , 99);
insert into Products values(055 , 'Tea & Coffee' , 20);
select * from Products;
insert into Orders values(101, 051 , 2);
insert into Orders values(102,052, 3 );
insert into Orders values(103, 053 , 5 );
insert into Orders values(104, 054 , 1 );
insert into Orders values(105, 055 , 2 );
select * from Orders;
